version: "3.8"
services:
  qnap-dashboard-proxy:
    build: .
    container_name: qnap-dashboard-proxy
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      PORT: "9999"
      QNAP_HOST: "10.10.20.5"
      QNAP_SNMP_USER: "jang"
      QNAP_SNMP_AUTH_PROTOCOL: "MD5"
      QNAP_SNMP_AUTH_PASSWORD: "djswi5fe"
      SONARR_HOST: "10.10.20.5"
      SONARR_PORT: "8989"
      SONARR_API_KEY: "9ccdc120b78844e4ade18dbad0e967bd"
      RADARR_HOST: "10.10.20.5"
      RADARR_PORT: "7878"
      RADARR_API_KEY: "864cb3c1831b4d49b9ec5de559d18f4a"
      SABNZBD_HOST: "10.10.20.5"
      SABNZBD_PORT: "8081"
      SABNZBD_API_KEY: "2c61eb166ba54cf8a1ce80e94a75fb53"
      QBIT_HOST: "10.10.20.5"
      QBIT_PORT: "8082"
      QBIT_USERNAME: "admin"
      QBIT_PASSWORD: "djswi5fe"
      EMBY_HOST: "10.10.20.5"
      EMBY_PORT: "8096"
      EMBY_API_KEY: "f3c07f7bc13a45178a5f0c60f26e3ede"
      TMDB_API_KEY: "a68379bfa6574857d9e9992375b16e5f"
