version: "3.8"
services:
  qnap-dashboard-proxy:
    build: .
    container_name: qnap-dashboard-proxy
    restart: unless-stopped
    ports:
      - "9999:9999"
    networks:
      - default
      - media_stack_arr-network
    environment:
      PORT: "9999"
      QNAP_HOST: "${QNAP_HOST}"
      QNAP_SNMP_USER: "${QNAP_SNMP_USER}"
      QNAP_SNMP_AUTH_PROTOCOL: "${QNAP_SNMP_AUTH_PROTOCOL}"
      QNAP_SNMP_AUTH_PASSWORD: "${QNAP_SNMP_AUTH_PASSWORD}"
      SONARR_HOST: "${SONARR_HOST}"
      SONARR_PORT: "${SONARR_PORT}"
      SONARR_API_KEY: "${SONARR_API_KEY}"
      RADARR_HOST: "${RADARR_HOST}"
      RADARR_PORT: "${RADARR_PORT}"
      RADARR_API_KEY: "${RADARR_API_KEY}"
      SABNZBD_HOST: "${SABNZBD_HOST}"
      SABNZBD_PORT: "${SABNZBD_PORT}"
      SABNZBD_API_KEY: "${SABNZBD_API_KEY}"
      QBIT_HOST: "${QBIT_HOST}"
      QBIT_PORT: "${QBIT_PORT}"
      QBIT_USERNAME: "${QBIT_USERNAME}"
      QBIT_PASSWORD: "${QBIT_PASSWORD}"
      EMBY_HOST: "${EMBY_HOST}"
      EMBY_PORT: "${EMBY_PORT}"
      EMBY_API_KEY: "${EMBY_API_KEY}"
      TMDB_API_KEY: "${TMDB_API_KEY}"
      HA_HOST: "${HA_HOST}"
      HA_PORT: "${HA_PORT}"
      HA_TOKEN: "${HA_TOKEN}"

networks:
  media_stack_arr-network:
    external: true
